apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::547641599748:role/eksctl-eksctl-demo-nodegroup-ng-94-NodeInstanceRole-2eF5Yhj84C4d
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::547641599748:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-28T15:39:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1315"
  uid: 304232b5-fe1a-42b7-ba48-4a895afaf428
